### ISSUE TITLE
Node.js compatibility

### ISSUE THREAD

**Issue by indexzero** [metmajer/dataseries.js#1]
First: nice work!

Any thoughts you releasing a node.js compatible version? If you rip our the CommonJS parts you can still do AMD for the browser if that's your cup of tea. 

```
node
> var ds = require('./src/dataseries');
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/charlie/OpenSource/dataseries.js/src/dataseries.js:1:63)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at repl:1:10
    at REPLServer.self.eval (repl.js:109:21)
    at rli.on.self.bufferedCmd (repl.js:258:20)
```

I could see this being very useful when working with data from [Godot](http://blog.nodejitsu.com/waiting-for-godot) and [window-streams](https://github.com/indexzero/window-stream).

**Comment by metmajer** [comment]
Glad to read that you like dataseries.js! It is still evolving and it would be awesome to see it included in your projects.
Note that I had planned to include moving average filters with v0.3.0 to smooth data drawn from probability distribution functions.

You should be save to require dataseries.js (from the top-level directory) in node.js.
The following snippet works for me:

``` javascript
var ds = require('./dataseries');

var data = ds.generators.f(ds.functions.identity)
    .inputs(ds.range(10))
    .values();

console.log(data);
```

Let me know if this works out for you and if this solves your problem!

**Comment by indexzero** [comment]
@metmajer It solves the problem but it makes node a second-class citizen. Why not publish it to npm?

**Comment by metmajer** [comment]
Sorry, not by intention, I just don't have any experience with node.
Could you take a look at the sources and provide instructions on how to make the project ready for node? Thanks!

**Comment by indexzero** [comment]
@metmajer Check. You got it. Expect a pull-request soon.

**Comment by metmajer** [comment]
@indexzero Any luck so far?
